In [4]:
import requests
import pandas as pd

In [6]:
url = "https://archive-api.open-meteo.com/v1/archive"

params = {
	"latitude": 24.8608,
	"longitude": 67.0104,
	"start_date": "2024-08-01",
	"end_date": "2026-08-01",
	"hourly": ["temperature_2m", "wind_speed_10m", "relative_humidity_2m", "surface_pressure"],
	"timezone": "auto",
}

response = requests.get(url, params)

In [7]:
data = response.json()

In [12]:
weatherData = pd.DataFrame(data["hourly"])

In [13]:
weatherData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure
0,2024-08-01T00:00,28.7,23.3,88,998.8
1,2024-08-01T01:00,28.6,22.4,88,998.2
2,2024-08-01T02:00,28.6,22.6,87,997.8
3,2024-08-01T03:00,28.7,23.9,85,997.5
4,2024-08-01T04:00,28.6,24.4,85,997.8

In [14]:
weatherData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  17544 non-null  object
 1   temperature_2m        17544 non-null  float64
 2   wind_speed_10m        17544 non-null  float64
 3   relative_humidity_2m  17544 non-null  int64
 4   surface_pressure      17544 non-null  float64
dtypes: float64(3), int64(1), object(1)
memory usage: 685.4+ KB

In [15]:
weatherData.time = pd.to_datetime(weatherData.time)

In [18]:
weatherData.time = weatherData.time.dt.tz_localize('Asia/Karachi')

In [19]:
weatherData.head()

,time,temperature_2m,wind_speed_10m,relative_humidity_2m,surface_pressure
0,2024-08-01 00:00:00+05:00,28.7,23.3,88,998.8
1,2024-08-01 01:00:00+05:00,28.6,22.4,88,998.2
2,2024-08-01 02:00:00+05:00,28.6,22.6,87,997.8
3,2024-08-01 03:00:00+05:00,28.7,23.9,85,997.5
4,2024-08-01 04:00:00+05:00,28.6,24.4,85,997.8

In [20]:
weatherData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17544 entries, 0 to 17543
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   time                  17544 non-null  datetime64[ns, Asia/Karachi]
 1   temperature_2m        17544 non-null  float64
 2   wind_speed_10m        17544 non-null  float64
 3   relative_humidity_2m  17544 non-null  int64
 4   surface_pressure      17544 non-null  float64
dtypes: datetime64[ns, Asia/Karachi](1), float64(3), int64(1)
memory usage: 685.4 KB